### ISSUE TITLE
Cannot create Scanforms from Batch IDs

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-go#11]
It appears that you cannot create a scanform from a batch ID and currently can only create a scanform from shipment IDs. The API Supports both, this library should allow for both as well.

eg code only allowing shipments:
```go
// CreateScanForm creates a scan form for the given Shipments.
//	c := easypost.New(MyEasyPostAPIKey)
//	out, err := c.CreateScanForm("shp_1", "shp_2")
func (c *Client) CreateScanForm(shipmentIDs ...string) (out *ScanForm, err error) {
	err = c.post(nil, "scan_forms", newscanFormRequest(shipmentIDs...), &out)
	return
}
```

**Comment by LoganSimonsen** [comment]
It kinda seems like this function was intended to hit the proper endpoint, but it's a GET instead of a POST? https://github.com/EasyPost/easypost-go/blob/master/batch.go#L187

but the comment makes it sound like this was meant to do the thing we want?

> // GetBatchScanForms generates a scan form for the batch.

**Comment by Justintime50** [comment]
#23 will correct this.
