### ISSUE TITLE
Incorrect Godoc link in README, does not point to v2

### ISSUE THREAD

**Issue by c9845** [EasyPost/easypost-go#130]
The link in "Alternatively, you can view the [GoDoc](https://pkg.go.dev/github.com/EasyPost/easypost-go)" points to the v1 version of this library, but v2 is the newest.  Godoc shows an alert in regards to this, but I think the README should be updated to point to the v2 version instead (https://pkg.go.dev/github.com/EasyPost/easypost-go/v2) since users should be using the newest version.

**Comment by Justintime50** [comment]
Great callout, thanks for reporting this!
