### ISSUE TITLE
Single or multiple codes when creating a refund

### ISSUE THREAD

**Issue by nwithan8** [EasyPost/easypost-go#149]
https://github.com/EasyPost/easypost-go/blob/effa70bb6840e4555ec93bb2e770e0315ac58fcb/tests/refund_test.go#L23

All other client libraries accept a list of tracking codes, but this seems to take a single code? It's a generic interface, so there's no type enforcement on this parameter (there probably should be?)

The cassette confirms that it's sending a single string rather than an array to the API, which doesn't seem to mind?
https://github.com/EasyPost/easypost-go/blob/effa70bb6840e4555ec93bb2e770e0315ac58fcb/tests/cassettes/TestRefundCreate.yaml#L152

An oddity of the API that needs to be abstracted?

**Comment by Justintime50** [comment]
Interesting. Let's patch the test to send a list of this single string and then let's make an internal task to create a struct for the creation fields in a future major release (breaking change).

**Comment by nwithan8** [comment]
Looks like Java and Ruby also sends a single string:
https://github.com/EasyPost/easypost-java/blob/3ae58c8ca9f1195df23efff3c80a76cbc142c322/src/test/java/com/easypost/RefundTest.java#L64
https://github.com/EasyPost/easypost-ruby/blob/bc77f40eaba63084472b6306a378e93f5a97e809/spec/refund_spec.rb#L13

But C# and Python sends a list (with one element):
https://github.com/EasyPost/easypost-csharp/blob/94611277b71fe00f45bcba03494dbc7c0fab578c/EasyPost.Tests/ServicesTests/RefundServiceTest.cs#L34
https://github.com/EasyPost/easypost-python/blob/69b6987dbdf055612c40a900a1abce76acdfd909/tests/test_refund.py#L15

**Comment by nwithan8** [comment]
@Justintime50 remind me what we did to address this?

**Comment by Justintime50** [comment]
We fixed the test per my suggestion above: https://github.com/EasyPost/easypost-go/commit/37505025b6683ff623a98c9e0ed5a0c0e1122419
