### ISSUE TITLE
[Feat]: Add Suppress ETD Undocumented Field to Shipment Options

### ISSUE THREAD

**Issue by c9845** [EasyPost/easypost-go#171]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

I currently have a "pre-this-golang library" implementation of the Easypost API using some custom HTTP request building.  I have been setting a "suppress_etd=true" field on the Shipment Options object as part of showing a secondary Airway Way Bill for international FedEx shipments.  This field is not present in the official Easypost Golang library.  Can it please be added?

```
v.Set("order[shipments]["+strconv.Itoa(index)+"][options][suppress_etd]", "true")
```

This field is undocumented in the Easypost API docs and I was informed about this field back in 2018 upon contacting support.  We use this to force FedEx to always return an Airway Way Bill along with the shipment label for international shipments.  We want to have the AWB label in conjunction with the standard shipping label for all international shipments so that we don't have to handle "is there an AWB" when we print the label(s); we just always handle printing both.

I would think adding ``SuppressETD bool `json:"suppress_etd"`` to the `ShipmentOptions` type would solve this.  Maybe add some documentation about when to use this field too since it is pretty specialized!

FYI: I have contacted support in regard to this and they told me to open this issue.

**Comment by Justintime50** [comment]
v2.17.0 is released with this shipment option included! Let support know about the documentation and we can look at that too separately.

**Comment by c9845** [comment]
@Justintime50 Thanks for this fix too!
