### ISSUE TITLE
[Feat]: Rate.Rate (and related fields) use flaot64, not string

### ISSUE THREAD

**Issue by c9845** [EasyPost/easypost-go#175]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

The Rate type has the fields Rate, RetailRate, ListRate being `string`.  Shouldn't these be `float64`?  

Other types are also affected: PickupRate.Rate.

**Comment by c9845** [comment]
Yes, I realize changing these fields from `string` to `float64` will break some (really, most or all) usage of this package.  Although, I suspect most usages are doing `strconv.ParseFloat` on the value stored in these fields anyway.

**Comment by Justintime50** [comment]
Hey @c9845, thanks for writing in.

The `rate`, `retail_rate`, and `list_rate` fields of a Rate object return from the API as `strings` so the library is correct as it's currently written. SmartRate on the other hand does return as `float64` for those same fields (this is also correct in the lib).

There have been occasions when a particular carrier's rates don't conform to that convention, in which case we'd love more information so we can correct that at the API level. If there are no issues beyond that, we'll go ahead and close this issue.

**Comment by c9845** [comment]
@Justintime50 Yes, I see the golang library matches the Easypost API docs.  I just figured setting the type to `float64` would make more sense, but I guess that would require reworking all the Easypost libraries to be consistent.  Is what it is, converting via `strconv` isn't the end of the world.
