### ISSUE TITLE
[Bug]: GetShipmentEstimatedDeliveryDate fails due to time parsing error when UPS is a carrier

### ISSUE THREAD

**Issue by coltmeister** [EasyPost/easypost-go#183]
### Software Version

2.19.0

### Language Version

Golang

### Operating System

OSX, Linux

### What happened?

Using the `/shipments/.../smartrate/delivery_date` endpoint, UPS rates come back with a date format that is different from what easypost-go is expecting, resulting in a time parsing error.

Here is an example UPS rate returned from the above endpoint:
```
        {
            "easypost_time_in_transit_data": {
                "days_in_transit": {
                    "percentile_50": 1,
                    "percentile_75": 1,
                    "percentile_85": 1,
                    "percentile_90": 1,
                    "percentile_95": 2,
                    "percentile_97": 2,
                    "percentile_99": 2
                },
                "easypost_estimated_delivery_date": "2023-06-29",
                "planned_ship_date": "2023-06-28"
            },
            "rate": {
                "carrier": "UPS",
                "carrier_account_id": "ca_a4be3a46b7bc4657ab2f6c898e1d7f6e",
                "created_at": "2023-06-28T14:52:39Z",
                "currency": "USD",
                "delivery_date": "Thu, 29 Jun 2023 10:30:00 GMT",
                "delivery_date_guaranteed": true,
                "delivery_days": 1,
                "est_delivery_days": 1,
                "id": "rate_7f560e1598024218a94aad5eca72851e",
                "list_currency": "USD",
                "list_rate": 70.0,
                "mode": "production",
                "object": "Rate",
                "rate": 45.57,
                "retail_currency": "USD",
                "retail_rate": 71.31,
                "service": "NextDayAir",
                "shipment_id": "shp_087a68cd07074e9da840971ced82cca5",
                "updated_at": "2023-06-28T14:52:39Z"
            }
        },
```

The specific field that is causing the error is:
`"delivery_date": "Thu, 29 Jun 2023 10:30:00 GMT",`

Paths to fix:
1. Modify EasyPost's internal API to return a standard date format for all dates across carrier rates.
2. Modify easypost-go to handle these different date formats.

<img width="459" alt="image" src="https://github.com/EasyPost/easypost-go/assets/10538007/3288a199-0161-49f7-9cff-9a3ad852b4d2">

### What was expected?

The `GetShipmentEstimatedDeliveryDate` returns UPS rates without erroring.

**Comment by coltmeister** [comment]
As a temporary bandaid, I've fixed this on a fork:

https://github.com/saltboxteam/easypost-go/commit/dce1d6fac5500fd046ff57d0855506ef023df07d

**Comment by Justintime50** [comment]
Thanks @coltmeister for reporting this and sharing the fixes from your fork. We'll take a look shortly and let you know our planned course of action. For the meantime, it's good to hear you have a bandaid solution.

**Comment by coltmeister** [comment]
Awesome, thanks for the response @Justintime50!
