### ISSUE TITLE
[Feat]: Return full Error response containing all details

### ISSUE THREAD

**Issue by elmarw** [EasyPost/easypost-go#185]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

The Error object only contains the main Error message. Is there a way to read the full Error response containing info about the fields that contain the errors?

**Comment by nwithan8** [comment]
The `APIError` object should have an `Errors` property that will expose information about any sub-errors, including invalid fields: https://pkg.go.dev/github.com/EasyPost/easypost-go/v2#APIError

Please let us know if this works for you.

**Comment by Justintime50** [comment]
Hey @elmarw, was @nwithan8's suggestion satisfactory? The main error message will only be the main error message; however, as mentioned, you can access the `errors` property which will contain an array of all the returned errors if applicable. There are additional properties on an Error object that may be useful to you. I'm going to close this issue, feel free to reopen if there was additional context missing or this isn't what you were after.
