### ISSUE TITLE
[Bug]: Missing readable field from `CarrierType`

### ISSUE THREAD

**Issue by sashahilton00** [EasyPost/easypost-go#221]
https://github.com/EasyPost/easypost-go/blob/083bfc98ea9bef90ec3cdb1f95749060138dbc02/carrier.go#L44-L48

In the documentation on Easypost's website (found [here](https://docs.easypost.com/docs/carrier-types)), the `CarrierType`object contains a field `readable` which is the display name of the carrier, as well as a `logo` field, though the latter seems to be `null` in all cases. Neither field is available in the Easypost SDKs, is this intentional or an oversight?

**Comment by Justintime50** [comment]
Hey @sashahilton00, this was most likely missed. We'd love (if you're interested) to have a PR put up to add those fields and we can get a release out to include them. Thanks for reporting this!

**Comment by sashahilton00** [comment]
@Justintime50 I'm happy to put a PR together, but the fields seem to be missing from the other SDKs as well - we're only using the Golang SDK currently, so can open a PR for this one, but not sure how you want to handle the missing fields in the others in terms of consistency?

**Comment by nwithan8** [comment]
> @Justintime50 I'm happy to put a PR together, but the fields seem to be missing from the other SDKs as well - we're only using the Golang SDK currently, so can open a PR for this one, but not sure how you want to handle the missing fields in the others in terms of consistency?

Our team will handle it in the other SDKs, thanks for bringing this to our attention.

**Comment by sashahilton00** [comment]
No problem. I'll submit a PR in a moment.

**Comment by sashahilton00** [comment]
One last thing, would it be possible to release this fix as `4.3.1`? It would save me needing to change back from my forked version in our code at a later date.

**Comment by nwithan8** [comment]
> One last thing, would it be possible to release this fix as `4.3.1`? It would save me needing to change back from my forked version in our code at a later date.

It was just released as version 4.3.1.
