### ISSUE TITLE
Use WithContext Correctly Throughout the Library

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-go#28]
# Summary

We have some tech debt where our non `WithContext` functions are not calling their associated `WithContext` functions in the Go lib. They should all follow the example here: https://github.com/EasyPost/easypost-go/issues/28 (Smartrate) so that non WithContext functions call their WithContext function (reuse it) and pass in `context.Background()` as the context. Let's fix it.

We should be adjusting all functions in this library to use the `WithContext` properly. We have a mix of each throughout the library and should really only be using one (example below).

## Acceptance Criteria

- [] Adjust the `WithContext` functions throughout the lib to work the same as the Smartrate one
- [] Upload a new screenshot of the test coverage once done

## Additional Info

From @qeubar 

> heh there are just inconsistencies in this library.
> 
> now that I'm looking further, the `XXXWithContext` functions seems to be the reason for these inconsistencies and are not setup ideally.
> 
> Here's how are we should approach this going forward:
> 
> ```
> func (c *Client) GetShipmentSmartrates(shipmentID string) (out []*Rate, err error) {
> 	return c.GetShipmentSmartratesWithContext(nil, shipmentID)
> }
> 
> func (c *Client) GetShipmentSmartratesWithContext(ctx context.Context, shipmentID string) (out []*Rate, err error) {
>         res :=  struct {
> 	       Smartrates *[]*Rate `json:"result,omitempty"`
>         }{Smartrates: &out}
> 	err = c.get(ctx, "shipments/"+shipmentID+"/smartrate", &res)
> 	return
> }
> ```

**Comment by nwithan8** [comment]
Any update on this?

**Comment by Justintime50** [comment]
It's in our backlog. We'll prioritize and complete like any other task in an upcoming sprint.

**Comment by Justintime50** [comment]
Closed via #91
