### ISSUE TITLE
FYI No mention of Go in the docs

### ISSUE THREAD

**Issue by G2G2G2G** [EasyPost/easypost-go#67]
There is no mention of Go really on any of these pages
https://www.easypost.com/getting-started
e.g.
>[Download an EasyPost Client Library](https://www.easypost.com/docs/libraries) in one following languages: Python, Ruby, PHP, Java, Node.js and C#(.NET). We also have community-supported client libraries like Perl and iOS on our Integrations page. If you prefer, you can always interact directly the REST API with cURL.

I think pages like this are maybe worded more appropriately:
https://www.easypost.com/ui-for-buying-shipments
>We'll be using Ruby, [Sinatra](http://www.sinatrarb.com/), and the [EasyPost Client Gem](https://github.com/EasyPost/easypost-ruby) in this example application, but this functionality could be integrated into any app written with Python, PHP, Java and other languages supported by the many EasyPost official [client libraries](https://www.easypost.com/docs/libraries).

As it ends in "and other languages" instead of being absolute. 

**Oh also mostly why this matters, in your code example "drop downs" there is no Go examples**

Sorry there isn't really any place to report this, no docs issues in your github or at least publicly available / nothing on the website (in your zendesk support? I don't need support, just letting you know).

Thanks

**Comment by jchen293** [comment]
Thank you for reporting this! We do have the plan to release the Go code example in our API Doc page, I will respond to you once the Go code example is added to our website. 

Meanwhile, you can find the Go code example in the library repository here: https://github.com/EasyPost/easypost-go/tree/master/examples

Please reply to this thread if you need some help with the Go library. Thanks!

**Comment by Justintime50** [comment]
You can also view the [GoDoc](https://pkg.go.dev/github.com/EasyPost/easypost-go) for library specific details.

**Comment by G2G2G2G** [comment]
Yea no worries about me specifically guys! I know my way around, just wanted to mention it about the site because at first I was considering copying the cURL examples and just implementing it in go. Then I considered running a different language for it but then I saw you actually did have Go lol.
Thanks!
