### ISSUE TITLE
New Release Never Pushed

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-go#8]
There were changes made 5 months ago and the library was released 7 months ago but there was no new release for the adjustments made 5 months ago so when downloading the library, you get an out of date library. Spent nearly two hours troubleshooting this until I found why my parameters weren't passing like they should.

Someone on the GitHub team needs to re-release, say `v1.0.1` as they were adjustments and not massive changes (to my knowledge) so that when you pull the library you get the new files. @jontsai

**Comment by Justintime50** [comment]
I apologize for the false alarm, go figure as soon as I submitted this I realized my error even after double checking. Closing.

**Comment by richshaffer** [comment]
Not sure why this was closed. It is legitimate. Anyone using modules and not explicitly specifying a version would have gotten the v1.0.0 tag, which didn't contain some bug fixes. (Legacy GOPATH go get will still fetch the default master branch, though.)

To fix this, I created a new release and tag for v1.0.1.
